// Generated by CoffeeScript 1.8.0
(function() {
  var exports;

  if ((typeof global !== "undefined" && global !== null) && (typeof require !== "undefined" && require !== null) && (typeof module !== "undefined" && module !== null) && (typeof cordova === "undefined" || cordova === null)) {
    exports = global;
    exports.chai = require('chai');
    exports.sinon = require('sinon');
    exports.sinonChai = require('sinon-chai');
  }

  exports.assert = exports.chai.assert;

  exports.expect = exports.chai.expect;

}).call(this);
